<?php

namespace AppBundle\Repository\Quiz;

/**
 * CandidateQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
